### ISSUE TITLE
为什么f.yml配置的字段和文档里不一样

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway-serverless-examples#21]
我看文档是 https://www.yuque.com/midwayjs/faas/serverless_yml

然后这个项目里的字段和文档不同，那么
1. 该用哪个？
2. 都兼容吗
3. 未来用哪个

**Comment by czy88840616** [comment]
哪个字段不一样？

**Comment by xmsz** [comment]
> 哪个字段不一样？

functions（文档有） 和 functionsRule（这个项目里有）

两个作用一样，但是字段和配置的内容不一样

**Comment by czy88840616** [comment]
文档里是最标准的字段，示例里的最后会在编译时变为文档里的字段。

**Comment by xmsz** [comment]
> 文档里是最标准的字段，示例里的最后会在编译时变为文档里的字段。

OK 那就是用文档里的是最保险
